import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { api } from "~/utils/api";
import { useConnect, useAccount } from 'wagmi';

const callbackUrl = '/protected'

export default function ClientPage() {
  const { connectors, connect, error, isLoading, data, isSuccess } = useConnect()
  const accountData = useAccount()

  console.log(connectors);
  
  const handleLogin = () => {
    connect({ connector: connectors[0] })
  }

  return (
    <>
      <Head>
        <title>Client page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h3>Client page</h3>
        <div className="flex flex-col gap-4 p-4">
          <p>{accountData.status}</p>
          <p>{isSuccess ? "success" : "not success"}</p>
          <p>{accountData.address}</p>
          <button
            className="border p-2 disabled:opacity-50"
            onClick={handleLogin}
            disabled={isLoading}
          >
            Log in with WalletConnect
          </button>
        </div>
      </main>
    </>
  );
}
