import Head from "next/head";
import { useState } from "react";
import { api } from "~/utils/api";

type InputRowProps = {
  label: string
  onChange: (value: string) => void
} & Omit<React.InputHTMLAttributes<HTMLInputElement>, "onChange">

function InputRow({ label, onChange, ...rest }: InputRowProps) { 
  return (
    <div className="flex gap-4">
      <label>{label}</label>
      <input
        className="border"
        type="text"
        onChange={(e) => onChange(e.target.value)}
        {...rest}
      />
    </div>
  )
}

export default function Claim() {
  const [address, setAddress] = useState("");
  const [name, setName] = useState("");
  const [id, setId] = useState("");
  
  const submitClaim = api.user.submitClaim.useMutation();

  return (
    <>
      <Head>
        <title>Claim death</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h3>Claim death</h3>
        <form
          onSubmit={(e) => {
            submitClaim.mutate({address, name, id})
            e.preventDefault();
          }}
          className="container flex flex-col items-center justify-center gap-4 px-4 py-16"
        >
          <div className="flex flex-col items-end">
            <InputRow label="Wallet address" value={address} onChange={setAddress} />
            <InputRow label="Name" value={name} onChange={setName} />
            <InputRow label="ID" value={id} onChange={setId} />
          </div>
          <button
            className="border p-2 w-20"
            type="submit"
          >
            Submit
          </button>
        </form>
      </main>
    </>
  );
}
